[package]
name = "esplugin-derive"
version = "0.1.0"
authors = ["agleave"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"

[dependencies.syn]
version = "1.0"
features = ["extra-traits"]